[package]
name = "tokio-utp"
version = "0.2.2"
authors = ["Carl Lerche <me@carllerche.com>", "Andrew Cann <shum@canndrew.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/carllerche/utp"
documentation = "https://docs.rs/utp2/0.1"
description = "tokio-based uTP implementation"

[dependencies]
mio = "0.6.9"
bytes = "0.4"
rand = "0.3"
slab = "0.4.0"
byteorder = "1.0"
log = "0.3.7"
smallvec = "0.4"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
unwrap = "1.1.0"
futures = "0.1.16"
void = "1"

[dev-dependencies]
env_logger = "0.4.2"
